# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Service containers to run with `runner-job`
    services:
      mongo:
        image: mongo:4.4.4
        ports:
          - 27017:27017
      cep:
        image: francescorivola/tribeca-cep:latest
        env:
          CEP_MONGODB_URL: mongodb://mongo:27017
          CEP_ADMIN_HTTP_HOST: 0.0.0.0
          CEP_ADMIN_HTTP_PORT: 8888
          CEP_EVENT_PROCESSING_HTTP_HOST: 0.0.0.0
          CEP_EVENT_PROCESSING_HTTP_PORT: 8889
        ports:
          - "8888:8888"
          - "8889:8889"
      cep-ui:
        image: francescorivola/tribeca-cep-ui:latest
        env:
          BASE_URL: http://localhost:8888
        ports:
          - "8080:80"
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - uses: actions/upload-artifact@v1
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
